// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Definiert Aktionen, die auf eine Datenbank angewendet werden können.
 */
export type DbAction = "read" | "readWrite" | "create" | "delete" | "alterDrop";
