// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DbConstraints = { where_clause: string | null, columns: Array<string> | null, limit: number | null, };
