// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Definiert Aktionen (HTTP-Methoden), die auf HTTP-Anfragen angewendet werden können.
 */
export type HttpAction = "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "*";
