// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionStatus } from "./PermissionStatus";

/**
 * Repräsentiert einen einzelnen Berechtigungseintrag im Manifest und im UI-Modell.
 */
export type PermissionEntry = { target: string, 
/**
 * Die auszuführende Aktion (z.B. "read", "read_write", "GET", "execute").
 */
operation?: string | null, 
/**
 * Optionale, spezifische Einschränkungen für diese Berechtigung.
 */
constraints?: Record<string, unknown>, 
/**
 * Der Status der Berechtigung (wird nur im UI-Modell verwendet).
 */
status?: PermissionStatus | null, };
