// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serialized representation of ExtensionError for TypeScript
 */
export type SerializedExtensionError = { code: number, type: string, message: string, extension_id: string | null, };
