// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Definiert Aktionen, die auf Shell-Befehle angewendet werden können.
 */
export type ShellAction = "execute";
