// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimit } from "./RateLimit";

export type WebConstraints = { methods: Array<string> | null, rate_limit: RateLimit | null, };
